### ISSUE TITLE
Fix website (github migration)

### ISSUE THREAD

**Issue by nricheton** [esigate/esigate#10]
- Fix wiki link
- Add 'Fork me on github' logo
- Add github as bug tracker and explain the end-of-life process for mantis
- Fix roadmap / changelog (add 'before 5.0' / from '5.0')
- Add latest logos in 'esigate is used by'

**Comment by fxbonnet** [comment]
Fixed:
   * wiki link
   * bug tracker
   * roadmap/changelog (prior to 5.0 and new from 5.0)

Todo:
   * explain the end-of-life process for mantisbt
