### ISSUE TITLE
mailto: links are incorectly rewritten

### ISSUE THREAD

**Issue by fxbonnet** [esigate/esigate#110]
A pull request has been submitted for branch 4.x but it has to be fixed in the trunk also.
https://github.com/esigate/esigate/pull/109

**Comment by nricheton** [comment]
I thought this is already fixed in trunk. We had this problem in esigate-5.0-beta2 and if was fixed in 5.0-beta3. 
We use beta3 and mailto links are working as expected

**Comment by fxbonnet** [comment]
You are right. I remember now we had a thread about it and it was fixed due to the improvements in the url rewriting algorithm. But the is no issue in the bug tracker and no unit test in the code for that. I will add one.
