### ISSUE TITLE
esi:choose executing include in when statement prematurely

### ISSUE THREAD

**Issue by StevenWeathers** [esigate/esigate#116]
I'm trying to test an ESI statement that works as far as which ESI it chooses, however its executing calls to the other ESI include as well.

```
<esi:choose>
            <esi:when test="'$(HTTP_COOKIE{username})' != ''">
                <esi:include src="/esi/include/a" />
            </esi:when>
            <esi:otherwise>
                <esi:include src="/esi/include/b" />
            </esi:otherwise>
 </esi:choose>
```

**Comment by fxbonnet** [comment]
Hello,
Good catch! I have been able to reproduce this issue. I am working on it.

**Comment by StevenWeathers** [comment]
Pulled your changes locally and built, seems to have fixed the issue thanks!

**Comment by StevenWeathers** [comment]
Didn't mean to close it, just comment ;)

**Comment by fxbonnet** [comment]
Yes, I finished testing on my side, it looks like the issue is solved. I close it.
