### ISSUE TITLE
Add $exists ESI test method

### ISSUE THREAD

**Issue by StevenWeathers** [esigate/esigate#117]
The function $exists to check to see if the 'item' exists. (E.g. cookies)
src: http://www.akamai.com/dl/technical_publications/esi_faq.pdf

```
<esi:choose>
  <esi:when test="$exists($(HTTP_COOKIE{'username'}))"
    [Take some action]
  </esi:when>
</esi:choose>
```

**Comment by fxbonnet** [comment]
This function is not part of the [ESI Language Specification](http://www.w3.org/TR/esi-lang), it is specific to Akamai but why not?

**Comment by fxbonnet** [comment]
If you would like to implement it, contributions are greatly appreciated.

**Comment by StevenWeathers** [comment]
Yea I believe its specific to Akamai.

I'll see if I can figure out how to implement it, Java is not my expertise ;)

**Comment by fxbonnet** [comment]
Variables and expressions are implemented in package "org.esigate.vars"

**Comment by StevenWeathers** [comment]
Alright I'll give it a shot, got the project building locally.

**Comment by StevenWeathers** [comment]
So I've been attempting to get this working in processOperators function.
Unfortunately I've been unsuccessful in getting into the first when statement.
Perhaps you could provide some guidance as to where I'm falling short...

Here's my JAVA code
```
Pattern AKAMAI_EXISTS_PATTERN = Pattern.compile("\\$exists\\((.*?)\\)");
Matcher AKAMAI_EXISTS_TEST = AKAMAI_EXISTS_PATTERN.matcher(test);

while (AKAMAI_EXISTS_TEST.find()) {
    String group = AKAMAI_EXISTS_TEST.group();
    String existsValue = group.substring(8, group.length() - 1);

    test = test.replace(group, existsValue + " != \"\"");
}
```

ESI Tags
```
<esi:choose>
    <esi:when test="$exists($(HTTP_COOKIE{'zipcode'}))">
        <esi:include src="/test-a" />
    </esi:when>
    <esi:otherwise>
        <esi:include src="/test-b" />
    </esi:otherwise>
</esi:choose>
```

**Comment by StevenWeathers** [comment]
Nevermind figured out the problem, $(HTTP_COOKIE{'zipcode'}) doesn't correctly get variable parsed because of the single quotes around cookie name.

**Comment by fxbonnet** [comment]
So you got it working?

**Comment by StevenWeathers** [comment]
Yes I've got it all working locally now :)

**Comment by fxbonnet** [comment]
Pull request merged! Thanks a lot for your contribution.
