### ISSUE TITLE
Add global onerror config option

### ISSUE THREAD

**Issue by StevenWeathers** [esigate/esigate#123]
So instead of manually adding onerror="continue" to every ESI tag it would be lovely to have a config option that allows one to specify a default action e.g. "onError=continue" or something.

-Thanks!

**Comment by StevenWeathers** [comment]
Started looking at how this could be implemented, or a temporary workaround for my use case could be implemented until a much broader approach.

I've found

```
boolean ignoreError = "continue".equals(includeTag.getAttribute("onerror"));
```

However upon changing that to always be true, breaks tests which breaks builds.
Tried commenting out/removing the tests around this feature, however other things are still erroring.

Perhaps you guys have an idea how to work around the tests aspect?

**Comment by fxbonnet** [comment]
Does this feature exist in Akamai ESI implementation?

**Comment by StevenWeathers** [comment]
No it does not

**Comment by StevenWeathers** [comment]
To clarify this is more of an edge case/workflow feature request, even if it's not implemented at the project level I'd love some guidance as to how I can tweak this for my instance.

-Thanks!

**Comment by StevenWeathers** [comment]
So far I've come up with adding the following in onTagEnd in esi/IncludeElement.java

```
if (Parameters.IGNORE_ESI_ERRORS.getValue(properties)) {
    ignoreError = "continue".equals("continue");
}
```

However I'm not quite sure how to get the properties loaded into that Class from the esigate.properties

**Comment by fxbonnet** [comment]
I cannot think of an easy way to integrate this in the code without changing a lot of things. And unfortunately I think we do not really want to integrate this feature as a standard feature in Esigate as our scope is to provide a reverse proxy with a cache, standard ESI features and the most usefull extensions from others ESI implementors like Akamai.
But maybe we can improve the global design of EsiGate in order to allow users to add this king of extensions. I have to think about it...

**Comment by fxbonnet** [comment]
Digging more in Akamai documentations, I have found something about a global configuration option "failure-action". Maybe this would fit your need? Maybe we could implement such a feature.
[A few explanations here](http://www.akamai.com/dl/technical_publications/akamai_esi_developers_guide.pdf) but there lack some example in the documentation:

**Comment by StevenWeathers** [comment]
Alright, for now I'll just look at how to change it to be always true and disable any test cases that conflict.
