### ISSUE TITLE
ESIGate does not seem to forward POST data

### ISSUE THREAD

**Issue by jbonachera** [esigate/esigate#128]
Hi, 

We are trying to setup ESIGate in front of a CAS-secured application. ESIGate is acting as a CAS Proxy.
CAS Authentication is working, but when we submit a POST request, ESIGate does not forward request data.
We did a network capture to confirm this, and it seems that ESIGate opens a connection to the application, sends the headers, and waits. After a short time, the application closes the connection , and fires a timeout.
When we replay the POST request from the curl command line tool (it's not easy, due to the CAS authentication), the requests works as expected.

Do you have any idea why esigate seems to eat our POST data ?

**Comment by fxbonnet** [comment]
Hi,
Which version of EsiGate are you using?
Could you set the logs to debug level and attach the log file to this issue?

**Comment by fxbonnet** [comment]
In addition, esigate.properties and web.xml file would be useful to understand what is happening.

**Comment by jbonachera** [comment]
We pursued our investigations, and it seems that the issue was caused by a CAS Single Sign Out Filter, so it's not related to ESIGate..
This filter seems to silently consume POST arguments, so we limited the filter-mapping to a single URL we do not send POST request to.

Sorry for the noise !
