### ISSUE TITLE
modify http response body

### ISSUE THREAD

**Issue by sim1st** [esigate/esigate#143]
Hello!

I am using Esigate as a reverse proxy server doing analyze Http Response Body.

I found a method which can modify Http Header value, but I wonder whether change(modify or manipulate) Http Response Body value.

Please let me know this method is available or not and Let me also know method name if possible.

In addition, I used ProxyEvent to analyze HTTP response body.

Thank you!

**Comment by fxbonnet** [comment]
Hi,

I wrote an example on how to modify http response bodies using Jsoup. You can find the code here:
https://github.com/fxbonnet/esigate-jsoup-example
Does it answer your question?

**Comment by sim1st** [comment]
Thanks for answering.

I read your code and I understand how to render replaced html file.

But can your code apply to not only HTML but also other formats(include attachment file)?

And one more, What is role of jsoup in your code?

**Comment by astik** [comment]
FX, correct me if I'm wrong =)
In the render signature, "String html" is not limited to HTML, it is in fact the complete stream managed through the extension. If you're dealing with XML, you'll have an XML content as a string.
Jsoup is only used here to illustrate a transformation from the input (HTML string load into jsoup) to the output (output into the writer).

**Comment by sim1st** [comment]
I know what you mean.

So other format might be changed by using jsoup either.

I'll try as your guides and Let you know whether it is successful.

But I have one more question, 

is RenderEvent only for dealing with HTTP Response?


If yes, How can I modify HTTP Request body?

**Comment by astik** [comment]
Jsoup can be used but you can use any other mechanism to work with the input, it is just used here as an example of how to change an HTML stream. If you're dealing with XML, instead of jsoup (which is not great to deal with XML), you can prefer to use other XML-specialized tools like SAX, DOM, ...

For the latest question, I'll let the experts come back to you =P

**Comment by alexist** [comment]
Hi,
Esigate provide extension mecanism. You can see the example in FX sample
https://github.com/fxbonnet/esigate-jsoup-example/blob/master/src/main/java/test/PageTransformer.java

You can implement your own Extension that will listen to some event.
Available events are listed here
http://www.esigate.org/reference.html#Events
http://www.esigate.org/esigate-core/apidocs/org/esigate/events/EventManager.html




2016-02-03 5:26 GMT+01:00 sim1st <notifications@github.com>:

**Comment by fxbonnet** [comment]
RenderEvent occurs after the response has been received, so it is too late to modify the request. If you want to modify the request, you need to attach an extension to another extension point like EVENT_FETCH_PRE

In addition to what Romain said, you can modify any response content (html or not) but by default, RenderEvent apply only to html or plain text responses.  You can change this behavior by setting configuration property parsableContentTypes to the list of mime types you want to transform.
http://www.esigate.org/reference.html#Configuration_directives

**Comment by sim1st** [comment]
Thanks all guys.

I'll try with RenderEvent and FechEvent to modify HTTP Request/Response Body

Temporally, I will close this issue until test is done.

Thanks again.

**Comment by sim1st** [comment]
I success to modify HTTP response body, but failed to modify HTTP request body.

In my code, process is like below:

Reading stream from HttpEntity -> Replacing text in entity -> Setting new entity into Request 

If stream was read, entity is consumed so I reset entity but Exception occurs.

Here is my part of code.

                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                httpEntity = requestBuilder.getEntity();
                HttpResponseUtils.writeTo(httpEntity, baos);
                byte[] bytes = baos.toByteArray();
                requestBody = new String(bytes, "UTF-8");
                requestBody = requestBody.replace("PD94bWwg", "SIMPLETEXT");                

                HttpEntity newEntity = new StringEntity(requestBody, ContentType.get(httpEntity));
                requestBuilder.setEntity(newEntity);
                httpRequest = RequestBuilder.post().setEntity(newEntity).build();
                httpRequestWrapper = httpRequestWrapper.wrap(httpRequest);

I think setting new entity process is wrong.

How can I fix it?

**Comment by fxbonnet** [comment]
What is the stacktrace of your Exception?

**Comment by sim1st** [comment]
Same as I asked here before

"Stream closed" 

![image](https://cloud.githubusercontent.com/assets/12407436/13095679/10030a6a-d557-11e5-8afd-3d9a18a8d825.png)

**Comment by fxbonnet** [comment]
It looks like EsiGate is still trying to use the incoming request entity that you already consumed instead of the new one you just built.
How do you pass the httpRequestWrapper you created?
It would be easier for me if you could share the complete code of your extension.

**Comment by sim1st** [comment]
I tried to another Event (EVENT_PROXY_PRE) after I failed with "EVENT_FECTH_PRE".

Logical process is almost same as previous one, but It worked!

Can you guess or explain why I success not FETCH but PROXY EVENT?

And I want to share my code privately, So please tell me how to share code just for you.

Thank you

**Comment by fxbonnet** [comment]
You can send me a zip file at fx.bonnet@esigate.org
I am interested also by the code that did not work with "EVENT_FECTH_PRE".
Which version of EsiGate are you using?

**Comment by sim1st** [comment]
I sended a mail to you with my code.

I installed Esigate version 5.1, but worked and modified code with 5.2(from github).

Please see the mail for getting into detail.

**Comment by fxbonnet** [comment]
Hi,

I had a look at your code. It looks like in the "EVENT_FECTH_PRE" version, you build a new HttpEntity, then a new request and wrap it to a HttpRequestWrapper but then you do nothing with it. So EsiGate is still trying to use the original HttpEntity you already consumed.

In order to pass your new HttpEntity you have to set it into the HttpRequestWrapper. Something like this should work:
```java
FetchEvent e = (FetchEvent)event;

if (EventManager.EVENT_FETCH_PRE.equals(id)) {
  HttpRequestWrapper httpRequestWrapper = e.getHttpRequest();
  if (httpRequestWrapper instanceof HttpEntityEnclosingRequest) {
	  HttpEntityEnclosingRequest httpEntityEnclosingRequest = (HttpEntityEnclosingRequest) httpRequestWrapper;
	  String requestBody = EntityUtils.toString(httpEntityEnclosingRequest.getEntity());
	  
	  LOG.info(new StringBuilder().append("Body = ").append(requestBody).toString());
	  
	  HttpEntity newEntity = new StringEntity(requestBody, "UTF-8");
	  httpEntityEnclosingRequest.setEntity(newEntity);
  }
}
```

**Comment by sim1st** [comment]
Thanks for helping me.

Maybe It will take more time to test because there is more urgent work...

I will close and report the result to you later.

Thanks again!!
