### ISSUE TITLE
Gzip content are always decompressed

### ISSUE THREAD

**Issue by alexist** [esigate/esigate#146]
I found an issue related to gzip response. It's look like esigate always decompress gzip response and deliver an uncompressed entity.

The response entity returned by httpclient is wrapped in GzipDecompressingEntity and response header doesn't contains Content-Encoding : gzip

The issue is due to HttpClientRequestExecutor : HttpClientBuilder contains a method disableContentCompression. The javadoc is more precise than the method name : "Disables automatic content decompression." 
As disableContentCompression, is enabled by default, the builder add the interceptor org.apache.http.client.protocol.ResponseContentEncoding. This interceptor wrap the entity response, decompres it, and remove Content-Encoding header

**Comment by nricheton** [comment]
Additional information (from your discussion on slack) : 

This is an issue for content which is not parsed by esigate (anything other than html, text, xml by default). This content should be left compressed, in cache and when delivering.

Html and text content is read by esigate, thus should be always decompressed (may be cached compressed, to save memory), parsed and compressed again on output (may be configured at the server level).

**Comment by alexist** [comment]
I fixed the issue related to content not parsed by esigate.

**Comment by fxbonnet** [comment]
Does `disableContentCompression() ` also mean that there is no more gzip between EsiGate and the provider? I mean does HttpClient still sends a `Accept-Encoding: gzip` header?

**Comment by alexist** [comment]
I have fixed the issue related to content not parsed by esigate.

**Comment by alexist** [comment]
No : disableContentCompression() will disable automatic content decompression.
I tested my fix on a real project where the javascript files were decompressed by esigate. Now,  javascript files are compressed.

**Comment by alexist** [comment]
https://bugs.openjdk.java.net/browse/JDK-8155588

**Comment by alexist** [comment]
https://github.com/esigate/esigate/pull/148
