### ISSUE TITLE
 Unable to compile class for JSP

### ISSUE THREAD

**Issue by alexist** [esigate/esigate#150]
There is an issue with latest JDK 8 oracle (u91). JUnit test on project esigate-app-casified-aggregator failed with a Jasper error :

2016-05-13 14:59:13.407:WARN:oejs.ServletHandler:/esigate-app-casified-aggregated1/block.jsp
org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP||PWC6199: Generated servlet error:|The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files||
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:123)

**Comment by fxbonnet** [comment]
The only code in that JSP is `<%=request.getRemoteUser() %>` also java.io.ObjectInputStream is a standard class from the JDK
Did you clean your work folder before testing?

**Comment by alexist** [comment]
Yes, i reproduce the error with a clean install. And the exception doesn't occure with java 7 or with java8+tomcat8x

**Comment by alexist** [comment]
https://bugs.openjdk.java.net/browse/JDK-8155588
