### ISSUE TITLE
Content-type Header value placed in Content-Encoding Header

### ISSUE THREAD

**Issue by Gruck** [esigate/esigate#159]
Hi,

I am currently playing arround with Esigate.
The http server i am using is pretty strict on expected values for Content-Encodig.

I seems like Content-Encoding and Content-Type get mixed up.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

In file https://github.com/esigate/esigate/blob/c06460a7a0ad71f2294bf07471fcf3c63823a720/esigate-servlet/src/main/java/org/esigate/servlet/impl/HttpServletRequestEntity.java

Possible fix : Replace ` String contentEncodingHeader = request.getCharacterEncoding();`
By ` String contentEncodingHeader = request.getHeader("Content-Encoding");`
Untested. Just derived form a simple code search within gitHub. Seems like this error is caused by the missing `getHeader()` Wrapper `getContentEncoding()`
Could be this had to be fixed somewhere else, but the fact this affectation deals with the two mixed up headers makes me think i point in the right direction.

Please feel free to discuss this by mail : gael.motte@sncf.fr or phone : +33 (0)1 80 46 21 31 

Cheers,
Gaël

**Comment by fxbonnet** [comment]
You are right, there is a mix between Content-Encoding and character encoding. We should fix this.
However I think most of the time these lines of code do nothing because request.getCharacterEncoding() is null due to the fact that browsers don't set the character encoding in the request.
Also I am not sure some browsers use any Content-Encoding in the request and if they did, how would the servlet engine handle this? Would it decode automatically the entity?
We definitely need some more testing about this.

Could you give some more details about your use case? What king of HTTP server are you using? What error do you get and how can I reproduce it?

**Comment by Gruck** [comment]
Hi,

Here are some details about the app i built when discovering this issue : 
Front : Backbone SPA. 
Back : NodeJS + [json-server](https://github.com/typicode/json-server) (express based mockup REST API server ), so no servlet engine.

1. The front calls the rest `POST` API with XHR and sets `Content-Type: application/json; charset=utf-8`
2. esigate gets the char encoding and affects it to `Content-Encoding` then calls the backend
3. Node + express refuse to process the request for `utf-8` is not a valid value for `Content-Encoding`.

I guess to reproduce, you just need to make an http `POST` to any node based backend through esigate.

Since the oppening of that issue, i added a request interceptor (middleware in terms of express) that overides this header. It works fine now with my current backend.

Eric Bretonniere, with whom i work at SNCF Fret for that study implemented an equivalent backend in both CXF and Spring MVC. From what he told me, it seems like they are not impacted by the issue. As if the header was discarded by the JVM, instead of causing a rejected request (`415 Unsupported Media Type`) like Express.

Please feel free to ask me any question that might help you reproduce this issue. :)
Cheers,

**Comment by fxbonnet** [comment]
I fixed the bug and added a test for that. Could you test with the latest snapshot?
Snapshots are deployed in Sonatype snapshot repository:
https://oss.sonatype.org/content/repositories/snapshots/

**Comment by Gruck** [comment]
Hi,

I just tested the  latest 5.3 snapshot. 
Looks fine to me, my nodeJS/express backend doesn't complain anymore about some illegal value for the `Content-Encoding` header.
