### ISSUE TITLE
Cache issue with query parameters

### ISSUE THREAD

**Issue by alexist** [esigate/esigate#162]
I'm wondering if there is not a cache issue in esigate. It's look like esigate cache doesn't handle query parameters, cached response are served regarless query parameters.

I wrote a Junit test that seem to reproduce the behaviour in MasterTest test case : 

MasterTest#testCacheIssue 

    public void testCacheIssue() throws Exception {
        // First request to this URL
        HttpClient client = HttpClients.createDefault();
        HttpGet request = new HttpGet(APPLICATION_PATH + "timeout.jsp?param1=test");
        HttpResponse response = client.execute(request);

        long before = System.currentTimeMillis();
        request = new HttpGet(APPLICATION_PATH + "timeout.jsp?param2=test");
        response = client.execute(request);
        long after = System.currentTimeMillis();
        assertEquals("Status should be 200", HttpServletResponse.SC_OK, response.getStatusLine().getStatusCode());
        assertTrue("Request should take more than 2 s as it is not in cache", after - before >= 1500);

        before = System.currentTimeMillis();
        request = new HttpGet(APPLICATION_PATH + "timeout.jsp?param2=test");
        response = client.execute(request);
        after = System.currentTimeMillis();
        assertEquals("Status should be 200", HttpServletResponse.SC_OK, response.getStatusLine().getStatusCode());
        assertTrue("Request should take less than 2 s as it is in cache", after - before < 1500);

    }

**Comment by nricheton** [comment]
Strange. I'm pretty sure there is already a unit test for this in the core (not using network however). 
I'll try your test. Could this be an issue in httpclient ?

**Comment by alexist** [comment]
Here the log : 2 queries has been done with different parameters .
You can see  for the first query:
10-02 12:04:38 42359    [qtp64236812-28] DEBUG org.apache.http.impl.client.cache.CachingExec  - Cache miss

For the second query :
10-02 12:04:52 56083    [qtp64236812-25] DEBUG org.apache.http.impl.client.cache.CachingExec  - Cache hit

[log_cache.txt](https://github.com/esigate/esigate/files/766480/log_cache.txt)


I wil ltry to debug this afternoon

**Comment by alexist** [comment]
There is no bug.

I was on the page http://localhost:8080/esigate-app-master/timeout.jsp. Esigate is configured with ServletExtension, and the query is not proxied to provider page. 

It's the app-master timeout.jsp who perform an esi:include of app-provider timeout.jsp page without any parameter. And app-provider page is put in cache.

I close the ticket.
