### ISSUE TITLE
Handle unknown Provider

### ISSUE THREAD

**Issue by ericbretonniere** [esigate/esigate#166]
Hi,

A unknown provider referenced in a IncludeTag (and not in esigate.properties) raises ConfigurationException that is not handled by try/except tag. This results a error page (jetty or tomcat or..) with esigate stacktrace. 

> "org.esigate.ConfigurationException: No configuration properties found for factory : webapp123456789
> 	org.esigate.DriverFactory.getInstance(DriverFactory.java:227)
> 	org.esigate.esi.IncludeElement.processPage(IncludeElement.java:153)
> 	org.esigate.esi.IncludeElement.onTagEnd(IncludeElement.java:81)
> ..."

We would like to render the except block instead of the error page.

Adding ConfigurationException to IOException and HttpErrorPage (or transforming ConfigurationException into HttpErrorPage) could change the behavior ( Class IncludeElement Method onTagEnd ).

What do you think about it ? Should I pull request?

Best regards,
Eric BRETONNIERE

 ```
  @Override
    public void onTagEnd(String tag, ParserContext ctx) throws IOException, HttpErrorPage {
 ....

   Exception currentException = null;
        // Handle src
        try {
            processPage(src, includeTag, ctx);
        } catch (IOException | HttpErrorPage **| ConfigurationException e**) {
            currentException = e;
        }

        // Handle Alt
        if (currentException != null && alt != null) {
            // Reset exception
            currentException = null;
            try {
                processPage(alt, includeTag, ctx);
            } catch (IOException | HttpErrorPage | **ConfigurationException e**) {
                currentException = e;
            }
        }

        // Handle onerror
        if (currentException != null && !ignoreError && !ctx.reportError(currentException)) {
            if (currentException instanceof IOException) {
                throw (IOException) currentException;
            } else if (currentException instanceof HttpErrorPage) {
                throw (HttpErrorPage) currentException;
            **} else if (currentException instanceof ConfigurationException) {
                throw (ConfigurationException) currentException;
            }**
            throw new IllegalStateException(
                    "This type of exception is unexpected here. Should be IOException or HttpErrorPageException.",
                    currentException);

        }
....
```

**Comment by fxbonnet** [comment]
Hi Eric,
The idea behind the current implementation is that try | attempt | except are used to deal with remote applications that are not available (http code 500 or timeout or network error...) whereas ConfigurationException is something that may occur during the development phase for example if you misspelled a provider name.
Don't you think catching ConfigurationExceptions may make it more difficult for developers to figure out what went wrong?

**Comment by nricheton** [comment]
Hi FX,

The use case is :
when a single esigate proxy is used in front of many apps, a faulty app can insert an include directive that blocks all page rendering, even if that app has just a small fragment with alternate versions.

I agree with the increased complexity for diagnostics/development,  but impact of this exception seems too big for production systems.

Maybe we can think of possible helpers :
- ensure ERROR logs in that case
- have a configuration option for dev mode (disable exception handling to catch all errors)

Nicolas

**Comment by fxbonnet** [comment]
Hi Nicolas,

In this case it sounds legitimate.
+1 for catching ConfigurationExceptions as well but log an ERROR
-1 for a new configuration option

@ericbretonniere pull request welcome (including unit test please)

**Comment by ericbretonniere** [comment]
Hi,
I am not sur to have understood
PullRequest with:
1) log error in case of unknow provider in includeElement
2) add "except behavior" in case of unknow provider ?
=> Should I add ConfigurationException in catch clause as I posted or convert configurationException to ErrorPage in processPage ?

**Comment by fxbonnet** [comment]
I don't think we need a specific except behaviour. You can add the ConfigurationException in the catch clause just like you posted and log error.

**Comment by fxbonnet** [comment]
Merged pull request
https://github.com/esigate/esigate/pull/167
