### ISSUE TITLE
CAS SpringSecutiry redirect issue

### ISSUE THREAD

**Issue by alexist** [esigate/esigate#51]
Spring-security integration in CASAuthenticationHandler seems to be buggy  :
- spring-security-redirect parameter is not/no more a standard spring-security parameter, and we can't use this parameter to customise redirection url
- provider Header location is not rewritten has expected. This is due to the addition, in CASAuthenticationHandler, of springSecurityUrl to the URL.

**Comment by fxbonnet** [comment]
* Removed spring-security-redirect parameter (not required anymore)
   * Migrated esigate-app-casified-aggregated2 test application to spring-security -> it works and is now covered by integration tests
